name: money_mate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  font_awesome_flutter:
  line_icons:
  google_fonts:
  fluttertoast: ^8.0.6
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  shared_preferences: ^2.0.5
  firebase_storage: ^8.0.2
  percent_indicator: ^3.0.1
  bottom_navy_bar: ^5.6.0
  animations: ^2.0.0
  get: ^4.1.4
  get_storage: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
